InputFolder: "data/input"
OutputFolder: "data/output"
ExecutionMode: "serialWindow"
SerialWindow:
  WindowTimeInSec: 2
Filter:
  Type: "bandpass"
  LowCut: 200
  HighCut: 3000
SpikeDetection:
  Method: "threshold"
  FactorPos: 6
  FactorNeg: 6
  RefractoryPeriod: 0.001
